#
# /etc/pacman.conf - Gaia Linux Package Manager Configuration
#

[options]
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HoldPkg     = pacman glibc systemd
Architecture = x86_64
CheckSpace
Color
ParallelDownloads = 5

SigLevel    = Optional TrustAll
LocalFileSigLevel = Optional

[gaia]
Server = file:///var/cache/gaia-repo
