---
defaultGroups:
    - users
    - sudo
    - cdrom
    - floppy
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - bluetooth

autologinGroup: autologin

sudoersGroup: sudo

setRootPassword: true

doAutologin: false

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords: true

user:
    shell: /bin/zsh
