---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
    requiredStorage: 8
    requiredRam: 1.0
    internetCheckUrl: https://google.com
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
