---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
timeout: 5
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
efiBootloaderId: "gaia"

# BIOS/Legacy fallback
installEFIFallback: true
