---
defaultGroups:
    - users
    - sudo
    - wheel
    - audio
    - video
    - plugdev
    - netdev
    - bluetooth
    - input
    - render
    - kvm

autologinGroup: autologin

sudoersGroup: wheel

setRootPassword: true

doAutologin: false

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords: true

user:
    shell: /bin/zsh
